name: CI

on:
  push:

  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: '1234!@#$'

          MYSQL_DATABASE: fieldops_integration
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
      - name: Install dependencies
        run: composer install --no-interaction --no-progress
      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            mysqladmin ping -h 127.0.0.1 -P 3306 -uroot -p'1234!@#$' && break
            sleep 1
          done
      - name: Create database
        run: mysql -h 127.0.0.1 -P 3306 -uroot -p'1234!@#$' -e "CREATE DATABASE IF NOT EXISTS fieldops_integration;"
      - name: Run migrations
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: fieldops_integration
          DB_USER: root
          DB_PASS: '1234!@#$'
        run: php tests/migrate_test_data.php
      - name: Reset test data
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: fieldops_integration
          DB_USER: root
          DB_PASS: '1234!@#$'
        run: php tests/reset_test_data.php
      - name: Run PHPUnit
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: fieldops_integration
          DB_USER: root
          DB_PASS: '1234!@#$'

        run: vendor/bin/phpunit
